/**
 * Generated by ChatGPT on 2024-06-10
 */

/**
 * Header Component Texts in Spanish
 */

const HEADER_TEXTS = {
    name: "Rupesh",
    home: "Inicio",
    about: "Acerca de mí",
    work: "Experiencia",
    credential: "Credenciales",
    contact: "Contacto",
};

/**
 * Home page texts in Spanish
 */

const SKILLS = [
    "Salesforce",
    "Componentes Web Lightning (LWC)",
    "Bryntum Grid",
    "Bryntum Scheduler",
    "Apex",
    "SOQL",
    "SOSL",
    "HTML",
    "CSS",
    "JavaScript",
    "Jest",
    "Git",
    "Jenkins",
    "JIRA",
];

const HOME_TEXTS = {
    profilePicAlt: "Foto de Rupesh Prajapat",
    greeting: "¡HOLA!",
    intro1: "SOY",
    intro2: "RUPESH",
    role: "Ingeniero de Software Senior / Desarrollador Salesforce / Consultor PSA",
    description:
        "Soy desarrollador Salesforce y full-stack engineer, apasionado por construir aplicaciones escalables y experiencias de usuario excepcionales.",
    technicalSkills: "Habilidades Técnicas",
    skills: SKILLS,
};

/**
 * About Me section texts in Spanish
 */

const ABOUT_ME = [
    "Soy Rupesh Prajapat, un Desarrollador Senior de Salesforce con más de 4 años de experiencia diseñando y desarrollando soluciones robustas en la plataforma Salesforce. Me especializo en Componentes Web Lightning (LWC), Apex y en construir interfaces de usuario de alto rendimiento con Bryntum Grid y Scheduler. Mi trabajo se centra en crear interfaces intuitivas y lógica de backend escalable alineada con las necesidades del negocio.",
    "Actualmente en Metacube, contribuyo al desarrollo del producto Professional Services Automation (PSA) de Certinia (anteriormente FinancialForce). He asumido responsabilidades clave como gestión de ciclos de lanzamiento, mentoría de miembros del equipo y resolución de desafíos técnicos complejos.",
    "Estoy certificado en Salesforce PD1, PD2 y JD1, y tengo experiencia práctica con herramientas como VS Code, Git, Jenkins y JIRA. Mi trayectoria comenzó con programación en C++ y evolucionó hacia el desarrollo de aplicaciones empresariales Salesforce, incluyendo herramientas internas como Permission Visualizer App.",
    "Fuera del trabajo, disfruto mentorizar nuevos desarrolladores, mantenerme actualizado con tecnologías emergentes y contribuir al crecimiento del equipo.",
];

const ABOUT_ME_TEXTS = {
    aboutMeHeading: "Sobre mí",
    aboutMeParagraphs: ABOUT_ME,
};

/**
 * Work Experience section texts in Spanish
 */

const WORK_EXPERIENCES = [
    {
        company: "Metacube Software",
        role: "Ingeniero de Software Senior | Cliente – Certinia (Anteriormente FinancialForce)",
        duration: "Abril 2024 - Presente",
        responsibilities: [
            "Gestiono actividades del equipo, planificación de lanzamientos y ejecución de proyectos para el producto Professional Services Automation (PSA).",
            "Identifico requisitos técnicos, riesgos y complejidades para próximos lanzamientos.",
            "Optimizé el rendimiento de los componentes UI LWC existentes desarrollados con Bryntum Grid y Scheduler.",
            "Imparto sesiones de formación en Salesforce y brindo orientación técnica a otros equipos de desarrollo.",
        ],
    },

    {
        company: "Metacube Software",
        role: "Ingeniero de Software | Cliente – Certinia (Anteriormente FinancialForce)",
        duration: "Enero 2021 - Marzo 2024",
        responsibilities: [
            "Especializado en desarrollo de UI de extremo a extremo en un equipo ágil, desde análisis de requisitos hasta aseguramiento de calidad.",
            "Desarrollé componentes LWC y código Apex reutilizable para mejorar la eficiencia.",
            "Migré múltiples páginas Visualforce a Componentes Web Lightning (LWC) modernos.",
            "Contribuí al desarrollo de los paquetes PSA Core y PSA Workspace.",
            "Mentoricé a nuevos Graduate Engineer Trainees (GETs).",
        ],
    },

    {
        company: "Metacube Software",
        role: "Graduate Engineer Trainee",
        duration: "Octubre 2020 - Diciembre 2020",
        responsibilities: [
            "Inicié mi carrera en Salesforce con un curso intensivo de 2 meses sobre fundamentos y estándares de desarrollo.",
            "Contribuí a tareas internas de desarrollo y al proceso de integración de nuevos empleados.",
        ],
    },
];

const WORK_EXPERIENCE_TEXTS = {
    workExperienceHeading: "Experiencia Laboral",
    workExperiences: WORK_EXPERIENCES,
};

/**
 * Credential section texts in Spanish
 */

const CERTIFICATIONS = [
    "Salesforce Platform Developer I",
    "Salesforce Platform Developer II",
    "Salesforce JavaScript Developer I",
];

const EDUCATIONS = [
    {
        degree: "Licenciatura en Tecnología de la Información",
        additionalInfo: "2016-2020 | CTAE Udaipur",
    },
    {
        degree: "Educación Secundaria Superior, PCM con Informática",
        additionalInfo: "2015 | JNV Tonk",
    },
];

const PROJECTS = [
    {
        name: "Mi Portafolio Personal",
        description:
            "Un sitio web de portafolio personal para mostrar mis habilidades, experiencia laboral y proyectos. Construido con React.js y alojado en GitHub Pages.",
        skills: "HTML5 | CSS3 | JavaScript | React.js",
    },
    {
        name: "Salesforce Permission App",
        description:
            "Aplicación de Salesforce diseñada para visualizar los permisos de objetos y campos de un usuario en un solo lugar utilizando Permission Sets y Perfiles.",
        skills: "Salesforce | LWC | Apex | HTML5 | CSS3 | JavaScript",
    },
    {
        name: "Aplicación de Compras en Salesforce",
        description:
            "Aplicación de compras creada usando una página Visualforce y desarrollando una acción rápida con componentes Aura y LWC.",
        skills: "Salesforce | LWC | Apex | HTML5 | CSS3 | JavaScript",
    },
    {
        name: "Juego Snake",
        description:
            "Juego creado en 2017 usando la biblioteca gráfica de C++, que gestionaba una matriz 2D de coordenadas X,Y.",
        skills: "C++ | Biblioteca Gráfica C++",
    },
];

const CREDENTIAL_TEXTS = {
    credentialHeading: "Credenciales y Educación",
    certificationsHeading: "Certificaciones",
    educationsHeading: "Educación",
    projectsHeading: "Proyectos",
    certifications: CERTIFICATIONS,
    educations: EDUCATIONS,
    projects: PROJECTS,
};

/**
 * Contact section texts in Spanish
 */

const CONTACT_TEXTS = {
    contactHeading: "Contacto",
    contactDescription:
        "Actualmente estoy abierto a nuevas oportunidades y colaboraciones. Ya sea que tengas una pregunta, una idea de proyecto o solo quieras conectarte, ¡no dudes en escribirme!",
    email: "Correo electrónico",
    emailAddress: "rupesh.p9696@gmail.com",
    socialProfiles: "Perfiles Sociales",
    githubLink: "https://github.com/rupesh0",
    linkedInLink: "https://www.linkedin.com/in/rupesh-prajapat/",
    trailheadLink: "https://trailhead.salesforce.com/en/me/rupesh.prajapat",
    emailMe: "Envíame un correo",
    linkedIn: "LinkedIn",
    downloadResume: "Descargar CV",
};

/**
 * Footer Component Texts in Spanish
 */

const FOOTER_TEXTS = {
    copyright: "© 2025 Rupesh Prajapat. Todos los derechos reservados.",
};

export {
    HEADER_TEXTS,
    HOME_TEXTS,
    ABOUT_ME_TEXTS,
    WORK_EXPERIENCE_TEXTS,
    CREDENTIAL_TEXTS,
    CONTACT_TEXTS,
    FOOTER_TEXTS,
};
