/**
 * Generated by ChatGPT on 2024-06-10
 */

import pd1Link from "../../assets/certificates/sf-pd1.pdf";
import pd2Link from "../../assets/certificates/sf-pd2.pdf";
import jd1Link from "../../assets/certificates/sf-jd1.pdf";

/**
 * Header Component Texts in Hindi
 */

const HEADER_TEXTS = {
    name: "रुपेश",
    home: "होम",
    about: "हमारे बारे में",
    work: "काम",
    credential: "प्रमाणपत्र",
    contact: "संपर्क करें",
};

/**
 * Home page texts in Hindi
 */

const SKILLS = [
    "Salesforce",
    "लाइटनिंग वेब कंपोनेंट्स (LWC)",
    "Bryntum Grid",
    "Bryntum Scheduler",
    "Apex",
    "SOQL",
    "SOSL",
    "HTML",
    "CSS",
    "JavaScript",
    "Jest",
    "Git",
    "Jenkins",
    "JIRA",
];

const HOME_TEXTS = {
    profilePicAlt: "रुपेश प्रजापत की तस्वीर।",
    greeting: "नमस्ते!",
    intro1: "मैं हूँ",
    intro2: "रुपेश",
    role: "सीनियर सॉफ्टवेयर इंजीनियर / Salesforce डेवलपर / PSA कंसल्टेंट",
    description:
        "मैं एक Salesforce डेवलपर और फुल-स्टैक इंजीनियर हूँ, जो स्केलेबल एप्लिकेशन और बेहतरीन उपयोगकर्ता अनुभव बनाने के लिए उत्साहित है।",
    technicalSkills: "तकनीकी कौशल",
    skills: SKILLS,
};

/**
 * About Me section texts in Hindi
 */

const ABOUT_ME = [
    "मैं रुपेश प्रजापत, एक सीनियर Salesforce डेवलपर हूँ, जिसे Salesforce प्लेटफ़ॉर्म पर मजबूत और स्केलेबल समाधान बनाने का 4+ वर्षों का अनुभव है। मैं लाइटनिंग वेब कंपोनेंट्स (LWC), Apex, और Bryntum Grid तथा Scheduler का उपयोग करके उच्च प्रदर्शन वाले यूज़र इंटरफेस बनाने में विशेषज्ञ हूँ। मेरा मुख्य फोकस उपयोगकर्ता-मित्र इंटरफेस और व्यापार जरूरतों के अनुरूप बैकएंड लॉजिक विकसित करना है।",
    "वर्तमान में Metacube में, मैं Professional Services Automation (PSA) उत्पाद के विकास में योगदान देता हूँ, जो Certinia (पूर्व में FinancialForce) के लिए है। मैंने रिलीज़ प्रबंधन, टीम मेंटरिंग, और जटिल तकनीकी समस्याओं के समाधान जैसी जिम्मेदारियों को संभाला है।",
    "मैं Salesforce PD1, PD2 और JD1 में प्रमाणित हूँ, और VS Code, Git, Jenkins, और JIRA जैसे टूल्स में वास्तविक अनुभव रखता हूँ। मेरी तकनीकी यात्रा C++ प्रोग्रामिंग से शुरू हुई और एंटरप्राइज-ग्रेड Salesforce एप्लिकेशन बनाने तक विकसित हुई, जिसमें Permission Visualizer App जैसे आंतरिक टूल शामिल हैं।",
    "काम के बाहर, मुझे नए डेवलपर्स का मार्गदर्शन करना, नवीनतम तकनीकों के साथ अपडेट रहना और टीम के विकास में योगदान देना पसंद है।",
];

const ABOUT_ME_TEXTS = {
    aboutMeHeading: "मेरे बारे में",
    aboutMeParagraphs: ABOUT_ME,
};

/**
 * Work Experience section texts in Hindi
 */

const WORK_EXPERIENCES = [
    {
        company: "Metacube Software",
        role: "सीनियर सॉफ्टवेयर इंजीनियर | ग्राहक – Certinia (पूर्व में FinancialForce)",
        duration: "अप्रैल 2024 - वर्तमान",
        responsibilities: [
            "Professional Services Automation (PSA) उत्पाद के लिए टीम गतिविधियों, रिलीज़ योजना और प्रोजेक्ट निष्पादन का प्रबंधन।",
            "आगामी रिलीज़ के लिए तकनीकी आवश्यकताओं, जोखिमों और जटिलताओं की पहचान।",
            "Bryntum Grid और Scheduler के साथ विकसित मौजूदा LWC UI कंपोनेंट्स का प्रदर्शन अनुकूलित किया।",
            "Salesforce प्रशिक्षण सत्र प्रदान करना और अन्य डेवलपमेंट टीमों को तकनीकी मार्गदर्शन देना।",
        ],
    },

    {
        company: "Metacube Software",
        role: "सॉफ्टवेयर इंजीनियर | ग्राहक – Certinia (पूर्व में FinancialForce)",
        duration: "जनवरी 2021 - मार्च 2024",
        responsibilities: [
            "एजाइल टीम में आवश्यकताओं के विश्लेषण से लेकर गुणवत्ता आश्वासन तक एंड-टू-एंड UI विकास में विशेषज्ञता।",
            "कुशलता बढ़ाने के लिए पुन: प्रयोज्य LWC कंपोनेंट्स और Apex कोड विकसित किया।",
            "कई Visualforce पेजों को आधुनिक LWC में माइग्रेट किया।",
            "PSA Core और PSA Workspace पैकेज के विकास में योगदान।",
            "नए Graduate Engineer Trainees (GETs) का मेंटरिंग।",
        ],
    },

    {
        company: "Metacube Software",
        role: "ग्रेजुएट इंजीनियर ट्रेनिंग",
        duration: "अक्टूबर 2020 - दिसंबर 2020",
        responsibilities: [
            "Salesforce में करियर की शुरुआत 2 महीने के क्रैश कोर्स से, जो विकास के मूल सिद्धांतों और मानकों पर आधारित था।",
            "आंतरिक विकास कार्यों और नए कर्मचारियों के ऑनबोर्डिंग में योगदान।",
        ],
    },
];

const WORK_EXPERIENCE_TEXTS = {
    workExperienceHeading: "कार्य अनुभव",
    workExperiences: WORK_EXPERIENCES,
};

/**
 * Credential section texts in Hindi
 */

const CERTIFICATIONS = [
    { name: "Salesforce Platform Developer I", link: pd1Link },
    { name: "Salesforce Platform Developer II", link: pd2Link },
    { name: "Salesforce JavaScript Developer I", link: jd1Link },
];

const EDUCATIONS = [
    {
        degree: "बैचलर ऑफ टेक्नोलॉजी इन इन्फॉर्मेशन टेक्नोलॉजी",
        additionalInfo: "2016-2020 | CTAE उदयपुर",
    },
    {
        degree: "सिनियर सेकेंडरी, PCM विद कंप्यूटर साइंस",
        additionalInfo: "2015 | JNV टोंक",
    },
];

const PROJECTS = [
    {
        name: "मेरी पोर्टफोलियो वेबसाइट",
        description:
            "एक व्यक्तिगत पोर्टफोलियो वेबसाइट जो मेरे कौशल, कार्य अनुभव और प्रोजेक्ट्स को प्रदर्शित करती है। React.js का उपयोग करके बनाई गई और GitHub Pages पर होस्ट की गई।",
        skills: "HTML5 | CSS3 | JavaScript | React.js",
    },
    {
        name: "Salesforce Permission App",
        description:
            "एक Salesforce एप्लिकेशन जो उपयोगकर्ता के ऑब्जेक्ट और फील्ड-लेवल अनुमतियों को एक ही स्थान पर विज़ुअलाइज़ करती है, Permission Sets और Profiles का उपयोग करके।",
        skills: "Salesforce | LWC | Apex | HTML5 | CSS3 | JavaScript",
    },
    {
        name: "Shopping App in Salesforce",
        description:
            "Visualforce पेज और Aura & LWC कंपोनेंट्स का उपयोग करके एक शॉपिंग एप्लिकेशन बनाई गई।",
        skills: "Salesforce | LWC | Apex | HTML5 | CSS3 | JavaScript",
    },
    {
        name: "Snake Game",
        description:
            "2017 में C++ ग्राफिक्स लाइब्रेरी का उपयोग करके बनाया गया खेल, जिसमें 2D X,Y coordinates का प्रबंधन किया गया।",
        skills: "C++ | C++ ग्राफिक्स लाइब्रेरी",
    },
];

const CREDENTIAL_TEXTS = {
    credentialHeading: "प्रमाणपत्र और शिक्षा",
    certificationsHeading: "प्रमाणपत्र",
    educationsHeading: "शिक्षा",
    projectsHeading: "प्रोजेक्ट्स",
    certifications: CERTIFICATIONS,
    educations: EDUCATIONS,
    projects: PROJECTS,
};

/**
 * Contact section texts in Hindi
 */

const CONTACT_TEXTS = {
    contactHeading: "संपर्क करें",
    contactDescription:
        "मैं वर्तमान में नई अवसरों और सहयोगों के लिए खुला हूँ। चाहे आपके पास कोई सवाल हो, प्रोजेक्ट आइडिया हो या बस जुड़ना चाहें, बेझिझक संपर्क करें!",
    email: "ईमेल",
    emailAddress: "rupesh.p9696@gmail.com",
    socialProfiles: "सोशल प्रोफाइल",
    githubLink: "https://github.com/rupesh0",
    linkedInLink: "https://www.linkedin.com/in/rupesh-prajapat/",
    trailheadLink: "https://trailhead.salesforce.com/en/me/rupesh.prajapat",
    emailMe: "मुझे ईमेल करें",
    linkedIn: "LinkedIn",
    downloadResume: "रिज़्यूमे डाउनलोड करें",
};

/**
 * Footer Component Texts in Hindi
 */

const FOOTER_TEXTS = {
    copyright: "© 2025 रुपेश प्रजापत। सर्वाधिकार सुरक्षित।",
};

export {
    HEADER_TEXTS,
    HOME_TEXTS,
    ABOUT_ME_TEXTS,
    WORK_EXPERIENCE_TEXTS,
    CREDENTIAL_TEXTS,
    CONTACT_TEXTS,
    FOOTER_TEXTS,
};
